apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
spec:
  replicas: 0 # TODO: currently 0, as the databases and its credentials as secrets are still missing
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-container
          # TODO: we have to change this to match the build from the CI/CD
          image: zbaakez/flou-todo:latest
          ports:
            - containerPort: 8080
          securityContext:
            runAsUser: 1000
          # TODO: set env variables for DB
