apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-container
          image: fschoenberger/todo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          securityContext:
            runAsUser: 1000
          env:
            - name: AUTH_HOST
              value: "http://authentication-service"
            - name: AUTH_PORT
              value: "8080"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: todo-db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-db-credentials
                  key: password
            - name: DB
              valueFrom:
                secretKeyRef:
                  name: todo-db-credentials
                  key: db_host
