apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-app
  template:
    metadata:
      labels:
        app: authentication-app
    spec:
      containers:
        - name: authentication-container
          image: fschoenberger/authentication:t2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          securityContext:
            runAsUser: 1000
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: auth-db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-db-credentials
                  key: password
            - name: DB
              valueFrom:
                secretKeyRef:
                  name: auth-db-credentials
                  key: db_host
            - name: COOKIE_DOMAIN
              value: http://34.154.103.76/
