apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  type: ClusterIP
  selector:
    app: authentication-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
