name: Build and Deploy Docker Images

# Triggered, when new Version-Tag is created
on:
  push:
    tags:
      - 'v*'

jobs:
  #--------------------------------------------------BUILD Section
  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
    # Check out codee and login to Docker Hub
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # github.ref_name
    # When Workflow is triggered through Version-Tag -> the ref_name should be something like v1.0.0

    # Backend - Authentication
    - name: Build Authentication Backend (Gradle)
      run: |
        cd flou/authentication
        ./gradlew dependencies
        ./gradlew bootJar
        cd ../..
    - name: Build and Push Authentication Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/authentication:${{ github.ref_name }} flou/authentication/
        docker push ${{ secrets.DOCKER_USERNAME }}/authentication:${{ github.ref_name }}

    # Backend - ToDo
    - name: Build ToDo Backend (Gradle)
      run: |
        cd flou/todo
        ./gradlew dependencies
        ./gradlew bootJar
        cd ../..
    - name: Build and Push ToDo Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/todo:${{ github.ref_name }} flou/todo/
        docker push ${{ secrets.DOCKER_USERNAME }}/todo:${{ github.ref_name }}

  # Frontend
    - name: Build Frontend (npm)
      run: |
        cd flou/frontend
        npm clean-install
        npm run build
        cd ../..
    - name: Build and Push Frontend Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.ref_name }} flou/frontend/
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.ref_name }}

  #--------------------------------------------------DEPLOY Section

  deploy:
    name: Deploy to GCP
    runs-on: ubuntu-latest
    needs: build

    # Setup everything for the Google Cloud and login
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: flou-cluster-1
          location: europe-west8-a

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f flou/authentication/k8s/deployment.yaml
          kubectl apply -f flou/authentication/k8s/service.yaml
          kubectl apply -f flou/todo/k8s/deployment.yaml
          kubectl apply -f flou/todo/k8s/service.yaml
          kubectl apply -f flou/frontend/k8s/deployment.yaml
          kubectl apply -f flou/frontend/k8s/service.yaml
