name: Deploy to GCP

# Build-Workflow has to be finished first 
on:
  workflow_run:
    workflows: ["Build Docker Images"]
    types:
      - completed


jobs:
  deploy:
    name: Deploy to GCP
    runs-on: ubuntu-latest

    # Setup everything for the Google Cloud and login
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker for GCR
      run: |
        gcloud auth configure-docker

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f flou/authentication/k8s/deployment.yaml
        kubectl apply -f flou/authentication/k8s/service.yaml
        kubectl apply -f flou/todo/k8s/deployment.yaml
        kubectl apply -f flou/todo/k8s/service.yaml
        kubectl apply -f flou/frontend/k8s/deployment.yaml
        kubectl apply -f flou/frontend/k8s/service.yaml
